### ISSUE TITLE
Shader Park code from explore page does not work in any of the templates

### ISSUE THREAD

**Issue by antithug** [shader-park/shader-park-examples#10]
If I copy the shaderpark code below (one of the examples from your main web page) into the spcode.js of the threejs example template, it does not work. It displays a blank blue polygon.

// from https://shaderpark.com/sculpture/-N-9T668AijcoYygOP4L
function fbm(p) {
  return vec3(
  	fractalNoise(p),
  	fractalNoise(p + 200),
  	0
  )
}

let timer = time*0.05
let p = enable2D()
p = 0.5*vec3(p.x, p.y, 0) + 5 * (timer / 10)
let composition = fbm( p + fbm( p + fbm( p )) ) *0.5+0.5
color( composition )

**Comment by antithug** [comment]
I just checked the es6-starter template, and the code does work, so it seems to be the threejs example that is failing in this case.

Perhaps something to do with enable2D?

**Comment by PWhiddy** [comment]
Hi,
Yes I do think it has to do with enable2D. I'm not actually sure yet what the ideal behavior should even be when using a 2D shader on a threejs mesh. 
For this particular shader, I can recommend replacing 
```
let p = enable2D()
```
with 
```
let p = getSpace()
```
And then adding some primitive at the end like `sphere(1)` or `box(1,1,1)`.  
You could then also replace `vec3(p.x, p.y, 0)` with just `p`.  
You can also try adding `setMaxIterations(1)` for something that will cover your whole mesh.

**Comment by antithug** [comment]
I see what you mean. No where to render the 2D. It works with the suggestions. Thanks, cool product.
